package p2pdops.dopsender.zshare_helpers

const val TYPE_REQUEST_NEXT_FILE = "TYPE_REQUEST_NEXT_FILE"
const val TYPE_RECEIVE_FILE_DATA = "TYPE_RECEIVE_FILE_DATA"
const val TYPE_REQUEST_DISCONNECT = "TYPE_REQUEST_DISCONNECT"