package p2pdops.dopsender.utils

const val RESULT_CODE_INPUT_DOCS = 301
const val RESULT_CODE_INPUT_APPS = 302
const val RESULT_CODE_INPUT_IMAGES = 303
const val RESULT_CODE_INPUT_VIDEOS = 304
const val RESULT_CODE_INPUT_AUDIO = 305
const val RESULT_CODE_INPUT_COMPRESSED = 306
